plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - config.ru
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*

FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - app/views/**/*

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 80
  IgnoreCopDirectives: true
  AllowedPatterns:
    - '^\s*# '
  Exclude:
    - config/initializers/new_framework_defaults_7_0.rb
    - test/components/previews/**/*

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

# Gives false positives when methods take an array literal as the first argument
Layout/SpaceBeforeBrackets:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/*_spec.rb"
    - spec/support/*

Lint/EmptyBlock:
  Exclude:
    - spec/factories/*

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - config/environments/*
    - config/routes.rb
    - spec/**/*_spec.rb
    - spec/support/*_shared_examples.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
    - test/components/previews/**/*

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb
    - lib/tasks/import_post_roster.rake

Rails/RakeEnvironment:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/application_controller.rb

RSpec/ExampleLength:
  Exclude:
    - spec/features/*
    - spec/system/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/*
    - spec/system/*

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  Exclude:
    - spec/features/*_spec.rb # within doesn't work with braces

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Style/SafeNavigation:
  Exclude:
    - app/views/**/*

Style/StringLiterals:
  Exclude:
    - config/importmap.rb # generated file
    - lib/tasks/*.rake
    - spec/**/*_spec.rb
    - spec/support/*_shared_examples.rb

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
